config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/random'
  resources :tournaments
  resources :teams
  resources :games
  resources :players
  root 'tournaments#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
    has_many :games;
    belongs_to :firstplace, class_name: "Player", foreign_key: "first"
    belongs_to :secondplace, class_name: "Player", foreign_key: "second"
    belongs_to :thirdplace, class_name: "Player", foreign_key: "third"
    TOURNAMENT_TYPES = ["SOLO", "DUO"]
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "yoroshiku", password: "yoroshiku", except: [:show, :index]
  
  # GET /tournaments
  # GET /tournaments.json
  def index
    @cm = Tournament.find 1
    @tournaments = Tournament.where.not(id:1).sort{|g| g.created_at.to_i}
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    if @tournament.id == 1
      @games = @tournament.games.sort_by(&:id).reverse
    else
      @games = @tournament.games.sort_by(&:id)
    end
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)
    respond_to do |format|
      if @tournament.save
        Game.batch_create!(@tournament.id, params[:data_file].path) if params[:data_file]
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        Game.batch_create!(@tournament.id, params[:data_file].path) if params[:data_file]
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :time, :tournament_type, :rule, :url, :first, :second, :third)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for @tournament, :html => { :multipart => true } do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :tournament_type, Tournament::TOURNAMENT_TYPES %>
  </div>
  <div class="field">
    <%= f.label :rule %><br>
    <%= f.text_field :rule %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "First place" %><br>
    <%= f.collection_select :first, Player.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label "Second place" %><br>
    <%= f.collection_select :second, Player.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label "Third place" %><br>
    <%= f.collection_select :third, Player.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label "Data file" %><br>
    <%= file_field_tag :data_file %>
  </div>
  <div class="actions">
    <%= f.submit "CREATE TOURNAMENT", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>
<%= render 'form' %>

app/views/tournaments/index.html.erb
<h2>Challenge Matches</h2>
<table class="table table-striped">
  <tbody>
    <tr>
      <td width="20%"><%= link_to @cm.name, @cm %></td>
      <td width="20%"><%= @cm.time %></td>
      <td width="20%"><%= @cm.tournament_type %></td>
      <td width="40%"><%= link_to @cm.url, @cm.url, target: "_blank" %></td>
    </tr>
  </tbody>
</table>
<h2>Tournaments</h2>
<table class="table table-striped">
  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td width="20%"><%= link_to tournament.name, tournament %></td>
        <td width="20%"><%= tournament.time %></td>
        <td width="20%"><%= tournament.tournament_type %></td>
        <td width="40%"><%= link_to tournament.url, tournament.url, target: "_blank" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Tournament', new_tournament_path, class: "btn btn-success" %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>
<%= render 'form' %>

app/views/tournaments/show.html.erb
<%= stylesheet_link_tag "//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" %>
<%= javascript_include_tag "//code.jquery.com/ui/1.11.4/jquery-ui.js" %>
<h2><%= @tournament.name %></h2>
<h4><%= @tournament.time %> | <%= @tournament.tournament_type %></h4>
<hr>
<h4>Rule:<%= link_to @tournament.rule, @tournament.rule, target: "_blank" %></h4>
<h4>URL:<%= link_to @tournament.url, @tournament.url, target: "_blank" %></h4>
<% if @tournament.firstplace %>
<hr>
<center><h4>1st (+80 ELO) <%= image_tag @tournament.firstplace.image_url, class: "logo margin-image" %>2st (+40 ELO) <%= image_tag @tournament.secondplace.image_url, class: "logo margin-image" %>3st (+20 ELO) <%= image_tag @tournament.thirdplace.image_url, class: "logo margin-image" %></h4></center>
<%  else %>
<%= link_to 'Edit', edit_tournament_path(@tournament), class: "btn btn-success" %>
<%= link_to 'Submit a match', new_game_path(tournament_id: @tournament.id), class: "btn btn-success" %>
<%  end %>
<hr>
<% if @tournament.id == 1 %>
  <center>
    <input type="text" id="datepicker" class="form-control" readonly style="width: 25%; display: -webkit-inline-box" placeholder="Click here to choose a date">
    <a class="btn btn-info" id="reset-button">Reset</a>
  </center>
  <br />
<% end %>

<table class="table table-striped">
  <tbody class="games">
    <% @games.each do |game| %>
      <tr class=<%= game.created_at.strftime("%d%m%Y")%>>
        <td style="vertical-align: middle; font-size: 15px;text-align: right;"><%= game.player1belo %>→<%= game.player1aelo %><%= link_to image_tag(game.player1.image_url, class: "logo"), player_path(game.player1) %><%= image_tag game.team1.logo, class: "logo" %></td>
        <td style="vertical-align: middle; font-size: 15px;text-align: center;"><b style="font-size:30px;"><%=game.result_in_text %></b><br><%= game.game_type %><a style="cursor: pointer;" onclick="showMatches('<%= game.created_at.strftime("%d/%m/%Y")%>')"><%= game.created_at.strftime("%d/%m/%Y") if @tournament.id==1 %></a></td>
        <td style="vertical-align: middle; font-size: 15px;text-align: left;"><%= image_tag game.team2.logo, class: "logo" %><%= link_to image_tag(game.player2.image_url, class: "logo"), player_path(game.player2) %><%= game.player2belo %>→<%= game.player2aelo %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<style>
 .logo {
   height: 50px;
 }
 
 .margin-image {
   margin-right: 50px;
 }

 .match-day a{
    color: red !important;
 }
</style>

<script>
  var game_dates = <%= raw @games.map{|game| game.created_at.strftime("%-d/%-m/%Y")}.uniq %>;

  $(function() {
    $("#datepicker").datepicker({
      beforeShowDay: function(d) {
        var date = d.getDate() + "/" + (d.getMonth() + 1) + "/" + d.getFullYear();
        return [true, game_dates.indexOf(date) > -1 ? "match-day" : ""];
      },
      dateFormat: "dd/mm/yy"
    })
    .on("input change", function(e) {
      showMatches(e.target.value);
    });
  });

  $("#reset-button").on("click", function(){
    $("#datepicker").datepicker("setDate", null);
    $(".games").children("tr").show();
  })

  function showMatches(date){
    $("#datepicker").val(date);
    var date_str = "." + date.replace(/\//g, "");
    $(".games").children("tr").hide();
    $(date_str).show();
  }
</script>