config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/random'
  resources :tournaments
  resources :teams
  resources :games
  resources :players
  root 'tournaments#index'

end

app/models/game.rb
require 'csv'
class Game < ActiveRecord::Base
    belongs_to :player1, class_name: "Player", foreign_key: "player1id"
    belongs_to :player2, class_name: "Player", foreign_key: "player2id"
    belongs_to :team1, class_name: "Team", foreign_key: "team1id"
    belongs_to :team2, class_name: "Team", foreign_key: "team2id"
    belongs_to :tournament
    after_create :set_belo_and_aelo_and_result
    
    TEAMS = {"bayern"=>1, "real"=>2, "barca"=>3, "psg"=>4, "manc"=>5, "chelsea"=>6, "juve"=>7, "arsenal"=>8, "dortmund"=>9, "manu"=>10, "atletico"=>11, "roma"=>12, "everton"=>13, "liverpool"=>14, "milan"=>15, "inter"=>16, "napoli"=>17, "lazio"=>18, "spurs"=>19}
    
    class << self
      def batch_create! tournament_id, filepath
        CSV.foreach(filepath) do |row|
          if row[0] == "no"
            next
          end
          @game = self.create player1id: Player.find_by_name(row[2]).id, player2id: Player.find_by_name(row[4]).id,
            team1id: TEAMS[row[6].downcase], team2id: TEAMS[row[7].downcase], 
            player1goal: row.last.first.to_i, player2goal: row.last.last.to_i, tournament_id: tournament_id, game_type: row[1]
        end
      end
    end
    
    def set_belo_and_aelo_and_result
      self.result = if self.player1goal > self.player2goal
        1
      elsif self.player1goal == self.player2goal
        0
      else
        -1
      end
      self.player1belo = player1.elo
      self.player2belo = player2.elo
      p1 = Elo::Player.new rating: self.player1belo
      p2 = Elo::Player.new rating: self.player2belo
      if result == -1
          p1.loses_from p2
      elsif result == 0
          p1.plays_draw p2
      else
          p1.wins_from p2
      end
      self.player1aelo = p1.rating
      self.player2aelo = self.player2belo - self.player1aelo + self.player1belo
      self.save
      player1.update_attributes elo: self.player1aelo
      player2.update_attributes elo: self.player2aelo
    end
    
    def result_in_text
      player1goal.to_s + " - " + player2goal.to_s
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "yoroshiku", password: "yoroshiku", except: [:show, :index]
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player1id, :player2id, :result, :player1belo, :player1aelo, :player2belo, :player2aelo, :team1id, :team2id, :player1goal, :player2goal, :tournament_id, :game_type)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <hr>
  <div class="field col-md-4">
    <%= f.collection_select :player1id, Player.all, :id, :name %>
    <%= f.collection_select :team1id, Team.all, :id, :name %>
  </div>
  <div class="field col-md-4">
    <%= f.collection_select :tournament_id, Tournament.all, :id, :name, {selected: params[:tournament_id]} %>
    <%= f.text_field :game_type %>
    <hr>
    <%= f.select :player1goal, 0..10 %> - <%= f.select :player2goal, 0..10 %>
  </div>
  <div class="field col-md-4">
    <%= f.collection_select :player2id, Player.all, :id, :name %>
    <%= f.collection_select :team2id, Team.all, :id, :name %>
  </div>
  <div style="clear:both;"></div>
  <hr>
  <div class="actions">
    <%= f.submit "SUBMIT GAME", class: "btn btn-success" %>
  </div>
<% end %>
<style>
  .field, .actions {
    text-align: center;
  }
  
  .field > select {
    height: 50px;
    font-size: 35px;
    margin-bottom: 10px;
    margin-top: 10px;
  }
</style>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Player1id</th>
      <th>Player2id</th>
      <th>Result</th>
      <th>Player1belo</th>
      <th>Player1aelo</th>
      <th>Player2belo</th>
      <th>Player2aelo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.player1id %></td>
        <td><%= game.player2id %></td>
        <td><%= game.result %></td>
        <td><%= game.player1belo %></td>
        <td><%= game.player1aelo %></td>
        <td><%= game.player2belo %></td>
        <td><%= game.player2aelo %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/games/show.html.erb
<div class="col-md-4">
  <%= image_tag @game.player1.image_url %> <%= image_tag @game.team1.logo, class: "logo" %>
  <hr>
  <%= @game.player1.name %>
  <hr>
  <%= @game.player1belo %>→<%= @game.player1aelo %>
</div>
<div class="col-md-4">
  <%= @game.tournament.name %><br/>
  <%= link_to "Back to tournament", tournament_path(@game.tournament), class: "btn btn-success" %>
  <hr>
  <span class="score"><%= @game.result_in_text %></span>
  <hr>
  <%= @game.game_type %>
</div>
<div class="col-md-4">
  <%= image_tag @game.team2.logo, class: "logo" %> <%= image_tag @game.player2.image_url %>
  <hr>
  <%= @game.player2.name %>
  <hr>
  <%= @game.player2belo %>→<%= @game.player2aelo %>
</div>

<style>
 .col-md-4 {
   text-align: center;
   font-size: 20px;
 }
 
 .logo {
   height: 100px;
 }
 
 .score {
   font-size: 50px;
 }
</style>