config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/random'
  resources :tournaments
  resources :teams
  resources :games
  resources :players
  root 'tournaments#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
    GAME_RESULT = {
        WON: 1,
        DRAWN: 0,
        LOST: -1
    }

    has_many :host_games, class_name: "Game", foreign_key: "player1id"
    has_many :guest_games, class_name: "Game", foreign_key: "player2id"
    
    def games
        (host_games.to_a | guest_games.to_a).sort_by &:created_at
    end
    
    def elo_data_by_event
        data = []
        Event.all.sort_by(&:id).each do |e|
            data << [e.name, eval(e.elos)[self.id]]
        end
        data
    end

    GAME_RESULT.keys.each do |const_name|
      define_method ("#{const_name.downcase}_games") {
        host_games.where(result: GAME_RESULT[const_name]) | guest_games.where(result: -GAME_RESULT[const_name])
      }
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "yoroshiku", password: "yoroshiku", except: [:index, :show]
  
  # GET /players
  # GET /players.json
  def index
    @players = Player.order(elo: :desc).to_a
    @group1 = @players.first(3)
    @group2 = @players.first(6) - @group1 = @players.first(3)
    @group3 = @players.last(4)
    @all_elo = Event.all.inject([]){|s,e| s|=eval(e.elos).values}
    @min = @all_elo.min - 20
    @max = @all_elo.max + 20
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @games = @player.games.sort_by(&:id).reverse
    @games_data = []
    @games.each_with_index do |g, i|
      @games_data << if g.player1id == @player.id
        [i+1, g.player1aelo]
      else
        [i+1, g.player2aelo]
      end
    end
    @events_data = []
    Event.all.sort_by(&:id).each do |e|
      @events_data << [e.name, eval(e.elos)[@player.id]]
    end
    @min = @games_data.map(&:last).min - 20
    @max = @games_data.map(&:last).max + 20
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :image_url, :elo)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :elo %><br>
    <%= f.number_field :elo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= line_chart Player.all.sort_by(&:id).map { |player|
    {name: player.name, data: player.elo_data_by_event}
}, width: "90%",min: @min, max: @max, discrete: true, library: {legend: { position: 'right', alignment: 'center'}, curveType: 'none'} %>
<center><h3 style="color:#ea6153;padding:10px;font-weight:bold;">GROUP 1</h3></center>
<table class="table table-striped" style="text-align: center;border: 1px rgb(237, 237, 237) solid">
  <thead>
    <tr>
      <th width ="10%" style="text-align: center">RANK</th>
      <th width ="10%"style="text-align: center">IMAGE</th>
      <th width ="30%"style="text-align: center">PLAYER</th>
      <th width ="10%" style="text-align: center">PLAYED</th>
      <th width ="10%" style="text-align: center">WON</th>
      <th width ="10%" style="text-align: center">DRAWN</th>
      <th width ="10%" style="text-align: center">LOST</th>
      <th width ="10%" style="text-align: center">POINTS</th>
    </tr>
  </thead>
  <tbody>
    <% @group1.each_with_index do |player, i| %>
      <tr>
        <td style="vertical-align: middle; font-size: 15px;"><%= i + 1 %></td>
        <td><%= link_to image_tag(player.image_url, style: "width: 50px"), player_path(player.id) %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.name %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.games.count %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.won_games.count %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.drawn_games.count %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.lost_games.count %></td>
        <td style="vertical-align: middle; font-size: 15px;"><%= player.elo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<center><h3 style="color:#2980b9;padding:10px;font-weight:bold;">GROUP 2</h3></center>
<table class="table table-striped" style="text-align: center;border: 1px rgb(237, 237, 237) solid">
  <tbody>
    <% @group2.each_with_index do |player, i| %>
      <tr>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= i + 4 %></td>
        <td width ="10%"><%= link_to image_tag(player.image_url, style: "width: 50px"), player_path(player.id) %></td>
        <td width ="30%" style="vertical-align: middle; font-size: 15px;"><%= player.name %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.won_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.drawn_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.lost_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.elo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<center><h3 style="color:#27ae60;padding:10px;font-weight:bold;">GROUP 3</h3></center>
<table class="table table-striped" style="text-align: center;border: 1px rgb(237, 237, 237) solid">
  <tbody>
    <% @group3.each_with_index do |player, i| %>
      <tr>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= i + 7 %></td>
        <td width ="10%"><%= link_to image_tag(player.image_url, style: "width: 50px"), player_path(player.id) %></td>
        <td width ="30%" style="vertical-align: middle; font-size: 15px;"><%= player.name %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.won_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.drawn_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.lost_games.count %></td>
        <td width ="10%" style="vertical-align: middle; font-size: 15px;"><%= player.elo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div class="profile">
  <%= image_tag @player.image_url %>
  <hr>
  <h3><%= @player.name %> - <%= @player.elo %> - (<%= "W#{@player.won_games.count}-D#{@player.drawn_games.count}-L#{@player.lost_games.count}" %>)</h3>
  <hr>
  <%= line_chart @events_data, min: @min, max: @max, discrete: true, library: {curveType: 'none', title: "ELO by events"}, id: "by_events" %>
  <%= line_chart @games_data, min: @min, max: @max, discrete: true, library: {curveType: 'none', title: "ELO by matches"}, id: "by_games" %>
  <table class="table table-striped" style="text-align: center">
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td style="vertical-align: middle; font-size: 15px;text-align: right;"><%= game.player1belo %>→<%= game.player1aelo %><%= image_tag game.player1.image_url, class: "logo" %><%= image_tag game.team1.logo, class: "logo" %></td>
          <td style="vertical-align: middle; font-size: 15px;text-align: center;"><b style="font-size:30px;"><%=game.result_in_text %></b><br><%= game.game_type %><br><%= game.tournament.name %></td>
          <td style="vertical-align: middle; font-size: 15px;text-align: left;"><%= image_tag game.team2.logo, class: "logo" %><%= image_tag game.player2.image_url, class: "logo" %><%= game.player2belo %>→<%= game.player2aelo %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style>
  .profile {
    text-align: center;
  }
  .logo {
    height: 50px;
  }
</style>

<script>
$("#by_events").click(function(){
  $("#by_events").hide(300);
  $("#by_games").show(300);
});
$("#by_games").click(function(){
  $("#by_games").hide(300);
  $("#by_events").show(300);
});
</script>