config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/random'
  resources :tournaments
  resources :teams
  resources :games
  resources :players
  root 'tournaments#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YORO PES - ELO SYSTEM</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "YORO PES - ELO SYSTEM", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if params[:controller] == "tournaments" %>"><%= link_to "HOME", root_path %></li>
        <li class="<%= "active" if params[:controller] == "players" %>"><%= link_to "ELO RANKING", players_path %></li>
        <li class="<%= "active" if params[:controller] == "static_pages" %>"><%= link_to "RANDOM", static_pages_random_path %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <br/><br/><br/>
  <%= yield %>
</div>
</body>
</html>